-- Creates the durable representation of the Payment aggregate root.
-- Flyway applies this file once and records version 1 in its schema history table.
CREATE TABLE payments (
    -- Technical aggregate identity generated by the application.
    payment_id UUID PRIMARY KEY,
    -- Business idempotency key: one order can initiate only one payment operation.
    order_id VARCHAR(100) NOT NULL,
    -- Exact decimal storage mirrors Money's non-negative, two-decimal policy.
    amount NUMERIC(19, 2) NOT NULL CHECK (amount >= 0),
    -- Currency is explicit even though the first version intentionally supports EUR only.
    currency VARCHAR(3) NOT NULL CHECK (currency = 'EUR'),
    -- Opaque provider token; raw card or bank-account data is never persisted here.
    payment_method_id VARCHAR(200) NOT NULL,
    -- Textual enum storage avoids coupling persisted meaning to an ordinal position.
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'AUTHORIZED', 'REJECTED')),
    -- Only successful authorization produces a provider reference.
    provider_reference VARCHAR(200),
    -- Only a definitive business rejection produces a failure reason.
    failure_reason VARCHAR(200),
    -- TIMESTAMPTZ stores instants independently of the database session time zone.
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    -- Hibernate increments this optimistic-lock token on every aggregate update.
    version BIGINT NOT NULL DEFAULT 0,

    -- Database-level idempotency remains authoritative under races or non-application writes.
    CONSTRAINT uk_payments_order UNIQUE (order_id),
    -- A provider authorization reference must never identify two local payments.
    CONSTRAINT uk_payments_provider_reference UNIQUE (provider_reference),

    -- Mirrors Payment's cross-field lifecycle invariant at the persistence boundary.
    CONSTRAINT ck_payments_lifecycle CHECK (
        (status = 'PENDING' AND provider_reference IS NULL AND failure_reason IS NULL)
        OR (status = 'AUTHORIZED' AND provider_reference IS NOT NULL AND failure_reason IS NULL)
        OR (status = 'REJECTED' AND provider_reference IS NULL AND failure_reason IS NOT NULL)
    ),
    -- Prevents impossible history even if data is written outside the domain model.
    CONSTRAINT ck_payments_timestamps CHECK (updated_at >= created_at)
);
