package com.orderflow.inventory.domain.model

import java.time.Instant

/**
 * Lifecycle state of a stock reservation.
 *
 * The deliberately small state machine supports allocation and compensation without allowing a
 * released reservation to become active again.
 */
enum class ReservationStatus {
    /** Stock is currently allocated to the associated order. */
    ACTIVE,

    /** Allocated stock has been returned to availability and cannot be returned a second time. */
    RELEASED,
}

/**
 * Domain entity recording a traceable allocation of stock to one order.
 *
 * A reservation belongs to an [InventoryItem] aggregate and is never persisted or changed on its
 * own. The timestamps and status preserve the history needed to distinguish an active allocation
 * from a compensation that has already been applied.
 *
 * @property id stable identifier used by release commands and persistence.
 * @property orderId order for which the units were allocated.
 * @property quantity positive number of allocated units.
 * @property status current lifecycle state.
 * @property reservedAt time at which the allocation was accepted.
 * @property releasedAt time at which the allocation was returned, or `null` while active.
 */
data class StockReservation(
    val id: ReservationId,
    val orderId: OrderId,
    val quantity: Quantity,
    val status: ReservationStatus,
    val reservedAt: Instant,
    val releasedAt: Instant?,
) {
    /**
     * Ensures lifecycle state and temporal data cannot contradict each other.
     *
     * Active reservations must not have a release timestamp, while released reservations must have
     * one. The condition is evaluated for both newly created and reconstituted instances.
     */
    init {
        require((status == ReservationStatus.ACTIVE) == (releasedAt == null)) {
            "Only released reservations may have a release time"
        }
    }

    /**
     * Transitions this reservation to [ReservationStatus.RELEASED].
     *
     * The operation is idempotent. Releasing an already released reservation returns the same
     * instance, retaining the original release timestamp and preventing callers from representing a
     * second stock restoration.
     *
     * @param at authoritative time at which the first release occurs.
     * @return a released copy for an active reservation, or this instance when already released.
     */
    fun release(at: Instant): StockReservation = when (status) {
        ReservationStatus.ACTIVE -> copy(status = ReservationStatus.RELEASED, releasedAt = at)
        ReservationStatus.RELEASED -> this
    }

    /** Factory operations that create valid reservation lifecycle states. */
    companion object {
        /**
         * Creates a newly accepted active reservation.
         *
         * The release timestamp is deliberately absent because no compensation has occurred yet.
         *
         * @param id identifier generated by the application layer for this reservation attempt.
         * @param orderId order receiving the allocation.
         * @param quantity units allocated to the order.
         * @param reservedAt authoritative acceptance time.
         * @return a valid active reservation.
         */
        fun active(
            id: ReservationId,
            orderId: OrderId,
            quantity: Quantity,
            reservedAt: Instant,
        ): StockReservation = StockReservation(
            id = id,
            orderId = orderId,
            quantity = quantity,
            status = ReservationStatus.ACTIVE,
            reservedAt = reservedAt,
            releasedAt = null,
        )
    }
}
